from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Dict
from enum import Enum

class Priority(Enum):
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"

class Frequency(Enum):
    ONCE = "once"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"

@dataclass
class Pet:
    name: str
    id: str
    species: str
    age: int
    breed: str = ""
    health_notes: str = ""
    owner_name: str = ""
    tasks: List[Task] = field(default_factory=list)

    def edit_info(self, **kwargs) -> None:
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)

    def edit_owner_name(self, new_owner_name: str) -> None:
        self.owner_name = new_owner_name

    def add_task(self, task: Task) -> None:
        if task not in self.tasks:
            self.tasks.append(task)

    def remove_task(self, task: Task) -> None:
        if task in self.tasks:
            self.tasks.remove(task)


@dataclass
class Task:
    pets: List[Pet] = field(default_factory=list)
    description: str = ""
    priority: Priority = Priority.NORMAL
    duration: int = 0  # minutes
    frequency: Frequency = Frequency.ONCE
    completed: bool = False

    def add_pet(self, pet: Pet) -> None:
        if pet not in self.pets:
            self.pets.append(pet)

    def remove_pet(self, pet: Pet) -> None:
        if pet in self.pets:
            self.pets.remove(pet)

    def edit_description(self, description: str) -> None:
        self.description = description

    def edit_priority(self, priority: Priority) -> None:
        self.priority = priority

    def edit_duration(self, duration: int) -> None:
        self.duration = duration

    def edit_frequency(self, frequency: Frequency) -> None:
        self.frequency = frequency

    def is_recurring(self) -> bool:
        return self.frequency != Frequency.ONCE
        
    def mark_completed(self) -> None:
        self.completed = True


@dataclass
class Scheduler:
    name: str = ""
    owner: Owner = None
    schedule: List[Task] = field(default_factory=list)
    explanation: str = ""
    
    def edit_name(self, name: str) -> None:
        self.name = name

    def generate_schedule(self) -> None:
        # Retrieve tasks from owner and sort by priority (HIGH first), then by duration (shortest first)
        if self.owner:
            tasks = self.owner.get_all_tasks()
            priority_order = {"low": 0, "normal": 1, "high": 2}
            self.schedule = sorted(tasks, key=lambda t: (-priority_order[t.priority.value], t.duration))
        else:
            self.schedule = []

    def generate_explanation(self) -> str:
        self.explanation = "Generated by default scheduling."  # placeholder
        return self.explanation

    def edit_explanation(self, explanation: str) -> None:
        self.explanation = explanation

    def get_tasks_by_pet(self) -> Dict[str, List[Task]]:
        from collections import defaultdict
        tasks_by_pet = defaultdict(list)
        for task in self.schedule:
            for pet in task.pets:
                tasks_by_pet[pet.name].append(task)
        return dict(tasks_by_pet)

    def get_schedule(self) -> List[Task]:
        return self.schedule


@dataclass
class Owner:
    pets: List[Pet] = field(default_factory=list)
    name: str = ""
    email: str = ""
    schedulers: List[Scheduler] = field(default_factory=list)
    available_time: List[str] = None

    def add_pet(self, pet: Pet) -> None:
        if pet not in self.pets:
            self.pets.append(pet)

    def remove_pet(self, pet: Pet) -> None:
        if pet in self.pets:
            self.pets.remove(pet)

    def edit_pet(self, pet: Pet, **kwargs) -> None:
        if pet in self.pets:
            pet.edit_info(**kwargs)

    def edit_owner_name(self, new_name: str) -> None:
        self.name = new_name
        
    def edit_onwer_email(self, new_email: str) -> None:
        self.email = new_email

    def add_task(self, pet: Pet, task: Task) -> None:
        if pet in self.pets:
            pet.add_task(task)

    def remove_task(self, pet: Pet, task: Task) -> None:
        if pet in self.pets:
            pet.remove_task(task)

    def get_all_tasks(self) -> List[Task]:
        all_tasks = []
        for pet in self.pets:
            all_tasks.extend(pet.tasks)
        return all_tasks

    def generate_scheduler(self, scheduler_name: str) -> Scheduler:
        p = Scheduler(owner=self, name=scheduler_name)
        p.generate_schedule()
        p.generate_explanation()
        self.schedulers.append(p)
        return p

    def remove_scheduler(self, scheduler: Scheduler) -> None:
        if scheduler in self.schedulers:
            self.schedulers.remove(scheduler)

    def add_available_time(self, time_slot: str) -> None:
        if self.available_time is None:
            self.available_time = []
        if time_slot not in self.available_time:
            self.available_time.append(time_slot)
    
    def remove_available_time(self, time_slot: str) -> None:
        if self.available_time and time_slot in self.available_time:
            self.available_time.remove(time_slot)
