from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class Pet:
    name: str
    species: str
    age: int
    breed: Optional[str] = None
    health_notes: Optional[str] = None
    owner_name: Optional[str] = None

    def edit_info(self, **kwargs) -> None:
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)

    def edit_owner_name(self, new_owner_name: str) -> None:
        self.owner_name = new_owner_name


@dataclass
class Task:
    pets: List[Pet] = field(default_factory=list)
    description: str = ""
    priority: str = "normal"
    duration: int = 0  # minutes

    def add_pet(self, pet: Pet) -> None:
        if pet not in self.pets:
            self.pets.append(pet)

    def remove_pet(self, pet: Pet) -> None:
        if pet in self.pets:
            self.pets.remove(pet)

    def edit_description(self, description: str) -> None:
        self.description = description

    def edit_priority(self, priority: str) -> None:
        self.priority = priority

    def edit_duration(self, duration: int) -> None:
        self.duration = duration


@dataclass
class Plan:
    tasks: List[Task] = field(default_factory=list)
    schedule: List[Task] = field(default_factory=list)
    explanation: Optional[str] = None

    def add_task(self, task: Task) -> None:
        self.tasks.append(task)

    def delete_task(self, task: Task) -> None:
        if task in self.tasks:
            self.tasks.remove(task)

    def generate_schedule(self) -> None:
        # Placeholder: sort by priority/duration or your own scheduling logic
        self.schedule = list(self.tasks)

    def generate_explanation(self) -> str:
        self.explanation = "Generated by default scheduling."  # placeholder
        return self.explanation

    def edit_explanation(self, explanation: str) -> None:
        self.explanation = explanation


@dataclass
class Owner:
    pets: List[Pet] = field(default_factory=list)
    owner_info: Optional[str] = None
    tasks: List[Task] = field(default_factory=list)
    plans: List[Plan] = field(default_factory=list)

    def add_pet(self, pet: Pet) -> None:
        if pet not in self.pets:
            self.pets.append(pet)

    def remove_pet(self, pet: Pet) -> None:
        if pet in self.pets:
            self.pets.remove(pet)

    def edit_pet(self, pet: Pet, **kwargs) -> None:
        if pet in self.pets:
            pet.edit_info(**kwargs)

    def edit_owner_info(self, owner_info: str) -> None:
        self.owner_info = owner_info

    def add_task(self, task: Task) -> None:
        self.tasks.append(task)

    def remove_task(self, task: Task) -> None:
        if task in self.tasks:
            self.tasks.remove(task)

    def generate_plan(self, plan_name: Optional[str] = None) -> Plan:
        p = Plan(tasks=list(self.tasks))
        p.generate_schedule()
        p.generate_explanation()
        self.plans.append(p)
        return p

    def remove_plan(self, plan: Plan) -> None:
        if plan in self.plans:
            self.plans.remove(plan)

